uploads = []

[[generated]]
id = "WlANRdIy1S_XbiXc2TMIf"
uri = "file://client/public/favicon.png"
type = "image"
title = "discreen gold favicon"

[[generated]]
id = "AoISZahSH3I1z1lD02rsk"
uri = "file://client/public/og-image.png"
type = "image"
title = "discreen og banner"

[[outputs]]
id = "TKWdsLrCrZe-Nvkya1FNL"
uri = "file://client/public/favicon.png"
type = "image"
title = "Logo Discreen"

[[outputs]]
id = "cHGH8JdaCys29CNgpG1fW"
uri = "file://scripts/index_telegram.txt"
type = "text"
title = "index_telegram.js"
